# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  workdir: &workdir
    working_directory: ~/module-source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/module-source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

jobs:
  install:
    <<: *workdir

    docker:
      - image: circleci/openjdk:8-jdk

    resource_class: large

    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: "Install Atlassian SDK"
          command: |
            wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz -P /opt/
            sudo tar -xvzf /opt/atlassian-plugin-sdk-4.0.tar.gz -C /opt/
            sudo mv /opt/atlassian-plugin-sdk-4.0 /opt/atlassian-plugin-sdk

      - run:
          name: "Check Atlassian SDK installation"
          command: |
            atlas-version

      - save_cache:
          paths:
            - ~/.m2
            - /opt/atlassian-plugin-sdk
          key: v2-dependencies-{{ checksum "pom.xml" }}

      - checkout

      - run:
          name: "Build artifacts"
          command: |
            atlas-package

      - run:
          name: "Copy artifacts"
          command: |
            mkdir /tmp/artifacts/
            cp /home/circleci/module-source/target/*.jar /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts/

      - *persist-workspace

workflows:
  version: 2
  build:
    jobs:
      - install